insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (1, 'DAVA Pharmaceuticals, Inc.', 'Rincon de Las Dalias', 5, 7, 'Polanco I Seccion');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (2, 'Cardinal Health', 'Eje Central', 57, 53, 'Torielo Guerra');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (3, 'Aurobindo Pharma Limited', 'Sindicato Nacional de Electricistas', 92, 67, 'Centro de la Ciudad de Mexico Area 5');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (4, 'Carilion Materials Management', 'Yacatas', 17, 67, 'Reforma Social');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (5, 'Uriel Pharmacy Inc.', 'Marina Nacional', 43, 99, 'Parque Industrial Metropolitano');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (6, 'Mary Kay Inc.', 'Rio Fuerte', 92, 93, 'San Rafael');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (7, 'Glenmark Generics Inc., USA', 'Montes Urales', 60, 39, 'Vallejo');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (8, 'Perrigo New York Inc', 'Segunda Cerrada Heroe de Nacozari', 90, 83, 'Interior Pedregal de Santo Domingo');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (9, 'Ningbo Kleen Products Co., Ltd.', 'Porto Alegre', 54, 27, 'Centro Area 4');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (10, 'Sun Pharmaceutical Industries Limited', 'Poniente 122', 54, 4, 'Olimpica');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (11, 'Zylera Pharmaceuticals, LLC', 'Yacatas', 56, 59, 'Benito Juarez');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (12, 'GlaxoSmithKline Consumer Healthcare LP', 'Yacatas', 35, 98, 'Santa Cruz Atoyac');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (13, 'Jubilant HollisterStier LLC', 'Ayuntamiento', 9, 69, 'El Retoño');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (14, 'CARDINAL HEALTH', '22 de Diciembre de 1860', 70, 44, 'Fraccionamiento Plazas de la Colina');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (15, 'Nelco Laboratories, Inc.', 'Morones Prieto', 32, 90, 'Extremadura Insurgentes');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (16, 'Merz Pharmaceuticals, LLC', 'Fuente de la Concordia', 57, 5, 'Republica');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (17, 'Supervalu Inc', 'Gonzalez Gallo', 58, 25, 'Lomas Verdes 3A Seccion');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (18, 'Pfizer Laboratories Div Pfizer Inc', 'Calle 12', 21, 15, 'Electra');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (19, 'Norwood Packaging Ltd.', 'Marti', 11, 51, 'Agustin Arriaga Rivera');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (20, 'Pharmaceutica North America', 'Mateo Saldaña', 18, 39, 'San Pedro de Los Pinos');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (21, 'Solco Healthcare US LLC', 'Instituto de Higiene', 57, 6, 'Ampliacion Granda');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (22, 'REMEDYREPACK INC.', 'Paseo de Las Americas', 34, 40, 'Jesus Gonzalez Ortega');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (23, 'Gurwitch Products, LLC', 'Agua Caliente', 4, 40, 'El Rosedal');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (24, 'J & A Medical Home Care Inc.', 'Fuente de la Concordia', 63, 64, 'Toluca de Lerdo Centro');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (25, 'Results RNA, LLC', 'Boulevard Anillo Periferico Adolfo Lopez Mateos', 90, 36, 'Copilco Universidad');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (26, 'Premier Value', 'Norte 16', 19, 85, 'Colonia');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (27, 'Trinity Pharmaceuticals, LLC', 'Jose Maria Castorena', 74, 19, 'Loma Bonita');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (28, 'Apotheca Company', 'Javier Barros Sierra', 39, 24, 'Los Alpes');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (29, 'Kmart Corporation', 'Diligencias', 56, 93, 'Nueva el Rosario');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (30, 'Gen-Source Rx', 'Munich', 50, 52, 'Interior Pedregal de Santo Domingo');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (31, 'Dista Products Company', 'Instituto de Higiene', 88, 66, 'Barrio Norte');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (32, 'CVS Pharmacy', 'Diligencias', 44, 65, 'Portales Norte');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (33, 'Nelco Laboratories, Inc.', 'Venustiano Carranza', 31, 60, 'Hipodromo Condesa');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (34, 'Portal Inc.', 'Bajada del Club', 17, 16, 'Lomas de San Francisco');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (35, 'Nelco Laboratories, Inc.', 'Marti', 70, 61, 'Nueva Vallejo');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (36, 'Allermed Laboratories, Inc.', 'Venustiano Carranza', 75, 60, 'La Constitucion Totoltepec');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (37, 'SJ Creations, Inc.', 'Calle 12', 13, 86, 'El Rosedal');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (38, 'Natural Ophthalmics, Inc', 'Marina Nacional', 52, 2, 'Tabacalera');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (39, 'Watson Pharma, Inc.', 'Marina Nacional', 34, 31, 'Polanco I Seccion');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (40, 'Major Pharmaceuticals', 'Eje Central', 43, 43, 'Defensores de la Republica');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (41, 'HANLIM PHARM. CO., LTD.', 'Nuevo Leon', 67, 78, 'Vista Hermosa');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (42, 'Safeway', 'Mazatlan', 87, 60, 'Los Alpes');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (43, 'Skin Alive, Ltd.', 'Tamaulipas', 24, 21, 'Veronica Anzures');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (44, 'Blenheim Pharmacal, Inc.', 'Mateo Saldaña', 27, 34, 'Santa Cruz Atoyac');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (45, 'Novartis Pharmaceuticals Corporation', 'Valle de Piedras Negras', 50, 98, 'Campestre Churubusco');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (46, 'Cadila Healthcare Limited', 'Miguel Angel de Quevedo', 20, 31, 'Juarez');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (47, 'CVS Pharmacy', 'Amores', 79, 80, 'Las Arboledas');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (48, 'Peaceful Mountain, Inc.', 'S. Lerdo de Tejada', 73, 10, 'Lazaro Cardenas');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (49, 'REMEDYREPACK INC.', 'San Isidro', 61, 99, 'San Pedro Martir');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (50, 'Major Pharmaceuticals', 'Boulevard San Juan Bosco', 54, 82, 'Las Arboledas');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (51, 'PD-Rx Pharmaceuticals, Inc.', 'Mayorazgo', 91, 68, 'Santa Fe');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (52, 'Goodier Cosmetics LP', 'Sindicato Nacional de Electricistas', 100, 45, 'Del Valle Centro');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (53, 'Paddock Laboratories, Inc.', 'Insurgentes Sur', 88, 20, 'Santo Tomas');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (54, 'Cover FX Skin Care, Inc.', 'Norte 5', 62, 72, 'Loma Bonita');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (55, 'Advacare Medical Services, Inc. dba Petersen Medical', 'Cerro de Las Torres', 79, 32, 'Roma Sur');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (56, 'Dispensing Solutions, Inc.', 'Marti', 29, 83, 'Los Alpes');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (57, 'Aloe Care International, LLC', 'Xelha', 60, 62, 'Ampliacion Granda');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (58, 'Allure Labs Inc.', 'Montes Urales', 49, 96, 'Felipe Pescador');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (59, 'Nelco Laboratories, Inc.', 'Gonzalez Gallo', 25, 28, 'Hipodromo');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (60, 'Home Sweet Homeopathics', 'Horacio Nelson', 4, 51, 'Benito Juarez');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (61, 'Apotheca Company', 'Tijuana', 22, 76, 'Copilco Universidad');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (62, 'Western Family Foods Inc', 'Munich', 84, 74, 'Cuauhtemoc');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (63, 'Novartis Pharmaceuticals Corporation', 'Independencia', 25, 6, 'Ampliacion Napoles');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (64, 'Coloplast Manufacturing US, LLC', 'Marina Nacional', 21, 58, 'Educacion');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (65, 'Griffin Home Health Care, Inc.', 'Tlalpan', 84, 47, 'Centro');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (66, 'Medline Industries, Inc.', 'Xelha', 88, 53, 'Ibarra');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (67, 'Teva Pharmaceuticals USA Inc', 'Gonzalez Gallo', 22, 44, 'Portales');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (68, 'Greenstone LLC', 'Navarra', 22, 47, 'San Rafael');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (69, 'Nelco Laboratories, Inc.', 'Jardines', 69, 46, 'Copilco Universidad');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (70, 'Dispensing Solutions, Inc.', 'Cuauhtemoc', 5, 2, 'Actipan');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (71, 'JHP Pharmaceuticals LLC', 'Universidad', 84, 100, 'San Rafael');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (72, 'REMEDYREPACK INC.', 'Calle 12', 6, 60, 'Portales');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (73, 'REMEDYREPACK INC.', 'Viaducto Miguel Aleman', 45, 70, 'Educacion');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (74, 'Nelco Laboratories, Inc.', 'Mexico Tacuba', 1, 57, 'Paseos de Churubusco');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (75, 'GlaxoSmithKline Consumer Healthcare LP', 'Viaducto Miguel Aleman', 73, 95, 'Alamos');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (76, 'Bracco Diagnostics Inc', 'Ayuntamiento', 83, 31, 'Los Alpes');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (77, 'Amgen Inc', 'Paseo de Las Americas', 28, 97, 'Educacion');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (78, 'Watson Pharma, Inc.', 'Jose Maria Castorena', 18, 20, 'San Rafael');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (79, 'ATOMY CO., LTD.', 'Garrido', 55, 53, 'Narvarte');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (80, 'Aidarex Pharmaceuticals LLC', 'San Francisco', 59, 38, 'Popotla');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (81, 'Physicians Total Care, Inc.', 'Eje Central', 82, 85, 'Centro');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (82, 'Native Remedies, LLC', 'Amores', 77, 72, 'San Pedro Martir');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (83, 'BioActive Nutritional, Inc.', 'Juan Vazquez de Mella', 91, 30, 'Agustin Arriaga Rivera');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (84, 'International Beauty Exchange', 'Lago Zurich', 40, 23, 'Hipodromo');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (85, 'Avon Products, Inc.', '22 de Diciembre de 1860', 9, 5, 'Centro de la Ciudad de Mexico Area 5');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (86, 'H&H Laboratories, Inc.', 'Boulevard San Juan Bosco', 26, 26, 'San Rafael');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (87, 'Kroger Company', 'Nicolas San Juan', 75, 33, 'Republica');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (88, 'Unifirst First Aid Corporation', 'Cerro de Las Torres', 19, 49, 'Benito Juarez');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (89, 'Nelco Laboratories, Inc.', 'Rincon de Las Dalias', 92, 15, 'Ibarra');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (90, 'Unichem Pharmaceuticals (USA), Inc.', 'Sindicato Nacional de Electricistas', 35, 64, 'Espartaco');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (91, 'Medline Industries, Inc.', 'Mateo Saldaña', 65, 48, 'Tepeyac Insurgentes');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (92, 'Philosophy Inc.', 'Garrido', 98, 10, 'Vista Hermosa');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (93, 'Cardinal Health', 'Bajada del Club', 39, 67, 'San Lorenzo Tezonco');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (94, 'CLINIQUE LABORATORIES INC.', 'Gonzalez Gallo', 60, 94, 'Felipe Pescador');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (95, 'West-ward Pharmaceutical Corp.', 'Insurgentes Sur', 40, 35, 'Huichapan');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (96, 'AMOREPACIFIC', 'Insurgentes Sur', 98, 16, 'Granjas Modernas');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (97, 'Watson Pharma, Inc.', 'Nuevo Leon', 15, 35, 'Hipodromo Condesa');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (98, 'Kremers Urban Pharmaceuticals Inc.', 'D', 64, 75, 'Nueva Vallejo');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (99, 'Mylan Pharmaceuticals Inc.', 'Benito Juarez', 64, 13, 'Condesa');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (100, 'Eduard Gerlach GmbH', 'Cerro de Las Torres', 90, 48, 'Torielo Guerra');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (101, 'Mylan Pharmaceuticals Inc.', 'Plaza de la Republica', 36, 5, 'Reforma');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (102, 'Stat Rx USA', 'Javier Barros Sierra', 52, 21, 'Vallejo');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (103, 'UCB, Inc.', 'Insurgentes Sur', 37, 2, 'Olimpica');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (104, 'Boy Butter Lubes', 'Boulevard San Juan Bosco', 97, 4, 'Loma Bonita');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (105, 'Dr. Reddy''s Laboratories Limited', 'Adolfo Lopez', 41, 11, 'Juarez');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (106, 'Jubilant HollisterStier LLC', 'Bajada del Club', 90, 88, 'Polanco I Seccion');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (107, 'HOMEOLAB USA INC', 'Nuevo Leon', 1, 12, 'Portales Norte');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (108, 'Washington University School of Medicine', 'Viaducto Miguel Aleman', 73, 13, 'Valle de San Fernando');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (109, 'Northstar Rx LLC', 'Lago Zurich', 40, 72, 'Santo Tomas');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (110, 'Jets, Sets, & Elephants Beauty Corp.', 'Calle 12', 73, 73, 'El Retoño');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (111, 'Hisamitsu America, Inc.', 'Mayorazgo', 65, 99, 'Juarez');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (112, 'Ventura International, LTD', 'S. Lerdo de Tejada', 70, 60, 'Veronica Anzures');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (113, 'The Hain Celestial Group, Inc.', 'Jesus del Monte', 71, 87, 'Del Valle');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (114, 'Stila Styles, LLC', 'Amores', 37, 26, 'Felipe Pescador');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (115, 'Allermed Laboratories, Inc.', 'Miguel Angel de Quevedo', 13, 68, 'Nueva el Rosario');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (116, 'Topco Associates LLC', 'Insurgentes Sur', 52, 48, 'Del Valle Centro');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (117, 'Par Pharmaceutical, Inc.', 'Chopo', 28, 25, 'Electra');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (118, 'Mylan Pharmaceuticals Inc.', 'Dr. Martinez del Rio', 43, 92, 'Del Valle');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (119, 'NCS HealthCare of KY, Inc dba Vangard Labs', 'Faisan', 1, 16, 'Tlacamaca');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (120, 'Sandoz Inc', 'Mexico Tacuba', 99, 10, 'Polanco I Seccion');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (121, 'Perrigo New York Inc', 'Montes Urales', 18, 67, 'Moderna');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (122, 'Physicians Total Care, Inc.', 'Adolfo Ruiz Cortines', 90, 30, 'Del Valle Centro');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (123, 'Mylan Pharmaceuticals Inc.', 'Norte 16', 11, 60, 'Centro Area 4');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (124, 'Rite Aid', 'Mazatlan', 19, 47, 'Copilco Universidad');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (125, 'Sun Pharmaceutical Industries Limited', 'Independencia', 91, 81, '7 de Julio');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (126, 'Topco Associates LLC', 'Lago Rodolfo', 39, 84, 'Jesus del Monte');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (127, 'ARMY AND AIR FORCE EXCHANGE SERVICE', 'Georgia', 92, 93, 'Santa Fe de la Laguna');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (128, 'SHISEIDO CO., LTD.', 'Guillermo Prieto', 43, 51, 'Alamos');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (129, 'Lake Erie Medical DBA Quality Care Products LLC', 'Cuauhtemoc', 57, 70, 'Loma Bonita');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (130, 'Roberts Oxygen Company, Inc.', 'Miguel Angel de Quevedo', 92, 2, 'Lomas Verdes 3A Seccion');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (131, 'Bryant Ranch Prepack', 'D', 33, 32, 'Colonia');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (132, 'Johnson & Johnson Healthcare Products, Division of McNEIL-PPC, Inc.', 'Mazatlan', 71, 39, 'Agua Caliente Seccion Pinos');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (133, 'Nelco Laboratories, Inc.', 'Marti', 39, 60, 'Granada');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (134, 'Best Accessory Group', 'Periodismo Jose Tocaven Lavin', 1, 60, 'San Jose del Consuelo');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (135, 'REMEDYREPACK INC.', 'Cuauhtemoc', 73, 59, 'Torielo Guerra');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (136, 'Keltman Pharmaceuticals Inc.', 'Circuito Emprendedores', 44, 56, 'Copilco Universidad');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (137, 'Cardinal Health', 'Fuente de la Concordia', 68, 81, '7 de Julio');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (138, 'Aphena Pharma Solutions - Tennessee, LLC', 'Juan Vazquez de Mella', 2, 31, 'Barrio Norte');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (139, 'Cantrell Drug Company', 'Jimenez', 9, 61, 'Lomas 4Ta. Seccion');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (140, 'Northstar Rx LLC', 'Monterrey', 33, 93, 'Tlacamaca');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (141, 'Hospira Worldwide, Inc.', 'S. Lerdo de Tejada', 58, 16, 'Tepeyac Insurgentes');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (142, 'REMEDYREPACK INC.', 'Insurgentes Sur', 31, 33, 'Portales');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (143, 'Aphena Pharma Solutions - Tennessee, LLC', 'Vicente Guerrero', 26, 26, 'El Rosedal');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (144, 'Care One (American Sales Company)', 'Mateo Saldaña', 3, 39, 'Paseos de Churubusco');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (145, 'Mylan Institutional LLC', 'Calle 12', 32, 9, 'Lomas Verdes 3A Seccion');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (146, 'Target Corporation', 'Benito Juarez', 3, 29, 'Espartaco');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (147, 'Nelco Laboratories, Inc.', 'San Isidro', 69, 6, 'Tabacalera');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (148, 'Camber Pharmaceuticals', 'San Isidro', 21, 97, 'Cuauhtemoc');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (149, 'Walgreen Company', 'Amores', 30, 49, 'Centro');
insert into Proveedor (numero_proveedor, razon_social, calle, num_int, num_ext, colonia) values (150, 'Kroger Company', 'Cerro de Las Torres', 16, 47, 'Lomas Verdes 3A Seccion');
