# Generated by Django 6.0.5 on 2026-05-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('metodo_pago', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=100)),
                ('num_int', models.CharField(max_length=10)),
                ('num_ext', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=50)),
                ('numero_tarjeta', models.CharField(max_length=20)),
                ('fecha_vencimiento', models.DateField()),
                ('esClienteOnline', models.BooleanField()),
                ('esClienteFisico', models.BooleanField()),
            ],
            options={
                'db_table': 'Cliente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_generico', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('laboratorio_fabricante', models.CharField(max_length=100)),
                ('forma_farmaceutica', models.CharField(max_length=50)),
                ('via_administracion', models.CharField(max_length=50)),
                ('presentacion', models.CharField(max_length=50)),
                ('potencia', models.CharField(max_length=50)),
                ('esteril', models.BooleanField()),
                ('clasificacion', models.CharField(max_length=50)),
                ('tipo_control', models.CharField(max_length=50)),
                ('precio_publico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_recibimiento', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('preparacion_oficial', models.TextField()),
                ('preparacion_pediatrica', models.TextField()),
                ('preparacion_dermatologica', models.TextField()),
            ],
            options={
                'db_table': 'Medicamento',
                'ordering': ['nombre'],
            },
        ),
    ]
